all:
  vars:
    control_plane_endpoint: 192.168.0.245
    load_balancer_ip_pool:
      - 192.168.0.224/27
metal:
  children:
    masters:
      hosts:
        butler: {ansible_host: 192.168.0.249, mac: '9c:6b:00:02:1a:4f', disk: nvme0n1, network_interface: eth0}
    workers:
      hosts:   
